---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
  - name: clone
    image: alpine
    commands:
      - apk add --no-cache git
      - git clone --recursive $DRONE_GIT_HTTP_URL .
      - git checkout $DRONE_COMMIT

  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.70.0
      validate: true

  - name: deploy
    image: appleboy/drone-scp
    settings:
      debug: true
      tar_tmp_path: /tmp/
      host: help.happydns.org
      target: /var/www/happydns.org/help/
      source: public/*
      strip_components: 1
      username:
        from_secret: ssh_username
      key:
        from_secret: deploy_key
      port:
        from_secret: ssh_port
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
