when:
  event:
    - push
    - tag
    - cron

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  - name: build
    image: hugomods/hugo:base
    commands:
      - hugo
      - cp public/en/404.html public/404.html
    environment:
      HUGO_ENVIRONMENT: production
