when:
  event:
    - push
    - tag
    - cron

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: registry.nemunai.re/plugins/hugo
    settings:
      hugo_version: 0.144.2
