clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build:
    image: plugins/hugo
    settings:
      hugo_version: 0.70.0
      validate: true

  publish-on-s3:
    image: plugins/s3
    settings:
      endpoint: https://storage.nemunai.re
      path_style: true
      bucket: happydomain-help
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      source: public/**/*
      strip_prefix: public/
      target: "/${CI_COMMIT_BRANCH//\\//-}"
