baseURL: https://help.happydomain.org/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

theme: hugo-theme-learn

languages:
  en:
    title: "happyDomain help center"
    weight: 1
    languageName: "English"
    landingPageURL: "/en"
    landingPageName: "<i class='fas fa-home'></i> Home"

  fr:
    title: "happyDomain centre d'aide"
    weight: 2
    languageName: "Français"
    landingPageURL: "/fr"
    landingPageName: "<i class='fas fa-home'></i> Accueil"

params:
  editURL: "https://framagit.org/happyDNS/help/-/blob/master/content/"
  description: "Finally a simple interface for domain names."
  themeVariant: "green"
  author: "The happyDNS team"
  showVisitedLinks: true
  disableBreadcrumb: false
  disableMermaid: true

outputs:
  home: [ "HTML", "RSS", "JSON"]

  shortcuts:
    name: "<i class='fab fa-gitlab'></i> Project sources"
    url: "https://framagit.org/happyDNS/"
    weight: 15
