baseURL: https://help.happydomain.org/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

theme: hugo-theme-relearn


languages:
  en:
    title: "happyDomain help center"
    languageName: "English"
    weight: 1
    params:
      landingPageName: "<i class='fas fa-home'></i> Home"

    menu:
      shortcuts:
        - name: "<i class='fab fa-gitlab'></i> Project sources"
          url: "https://framagit.org/happyDomain/"
        - name: "<i class='fas fa-comments'></i> Matrix channel"
          url: "https://matrix.to/#/#happyDNS:matrix.org"
        - name: "<i class='fab fa-mastodon'></i> Mastodon"
          url: "https://floss.social/@happyDomain"

  fr:
    title: "happyDomain centre d'aide"
    weight: 2
    languageName: "Français"
    params:
      landingPageName: "<i class='fas fa-home'></i> Accueil"

    menu:
      shortcuts:
        - name: "<i class='fab fa-gitlab'></i> Sources"
          url: "https://framagit.org/happyDomain/"
        - name: "<i class='fas fa-comments'></i> Canal Matrix"
          url: "https://matrix.to/#/#happyDNS:matrix.org"
        - name: "<i class='fab fa-mastodon'></i> Mastodon"
          url: "https://floss.social/@happyDomain"

params:
  editURL: "https://framagit.org/happyDNS/help/-/blob/master/content/"
  description: "Finally a simple interface for domain names."
  author:
    name: "The happyDNS team"
  showVisitedLinks: true
  disableMermaid: true
  themeVariant:
    - auto
    - green


outputs:
  home: [ "HTML", "RSS", "SEARCH"]
